CREATE TABLE `t_icbc_metal` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `upordown` int(10) DEFAULT NULL,
  `lowmiddleprice` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL,
  `updown_d` int(10) DEFAULT NULL,
  `buyprice` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '买入价格',
  `unit` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '单位',
  `prodcode` varchar(32) COLLATE utf8mb4_bin DEFAULT NULL,
  `ebuyprice` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL,
  `openprice_dr` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL,
  `openprice_dv` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL,
  `metalname` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '贵金属名称',
  `esellprice` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL,
  `metalflag` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL,
  `sellprice` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '卖出价格',
  `middleprice` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL,
  `updown_y` int(10) DEFAULT NULL,
  `openprice_yr` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL,
  `topmiddleprice` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL,
  `currcode` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL,
  `data_time` datetime DEFAULT NULL COMMENT '数据获取时间',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='账户贵金属';
